/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsfinalproject;

import static dsfinalproject.DSFinalProject.Array1;
import static dsfinalproject.DSFinalProject.Array2;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author AQIB HASSAN
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
     long startTimeQ; //start time
        long endTimeQ;   //end time
        double timeQ;    //time difference
         long startTimeB; //start time
        long endTimeB;   //end time
        double timeB;    //time difference
    boolean loading=false;
    boolean Quick=false;
    boolean Bubble=false;
   int TimeComplexityQ=0;
   int CKQ=0;
   int SPQ=0;
   int CKB=0;
   int SPB=0;
   int TimeComplexityB=0;
    public MainFrame() {
      
        initComponents();
         jLabel8.setVisible(loading);
         jLabel7.setVisible(false);
         jLabel9.setVisible(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        backImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1203, 637));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1203, 637));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsfinalproject/loading.gif"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(500, 200, 280, 250);

        jScrollPane1.setForeground(new java.awt.Color(0, 204, 204));

        jTextArea1.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 204, 204));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 170, 170, 400);

        jScrollPane2.setForeground(new java.awt.Color(0, 204, 204));

        jTextArea2.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 204, 204));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 170, 171, 396);

        jScrollPane3.setBackground(new java.awt.Color(0, 204, 204));
        jScrollPane3.setForeground(new java.awt.Color(0, 204, 204));

        jTextArea3.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 204, 204));
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(450, 170, 171, 396);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("  Bubble Sort");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 130, 170, 40);

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("   Quick Sort");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 130, 170, 40);

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText(" Original Data");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 130, 170, 40);

        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("Sorting Algorithm Through File");

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 807, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 40);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Bubble Sort");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 580, 170, 37);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setText("Quick Sort");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 580, 170, 37);

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText("Radom file creater");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 240, 180, 40);

        jLabel6.setBackground(new java.awt.Color(153, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Enter no of data ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(630, 130, 160, 60);

        jLabel9.setBackground(new java.awt.Color(204, 0, 51));
        jLabel9.setFont(new java.awt.Font("Courier New", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText(" Quick Sort Wins ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(770, 290, 390, 80);

        jTextField1.setBackground(new java.awt.Color(153, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 204, 204));
        jTextField1.setText("0");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(630, 180, 160, 50);

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 204));
        jButton4.setText("Refresh");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 580, 160, 40);

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 204));
        jButton5.setText("CLEAR");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(960, 570, 170, 40);

        jScrollPane4.setForeground(new java.awt.Color(0, 204, 204));

        jTextArea4.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(0, 204, 204));
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(640, 470, 250, 160);

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Time of Bubble:");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(790, 60, 220, 40);

        jLabel14.setBackground(new java.awt.Color(204, 0, 51));
        jLabel14.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 51));
        jLabel14.setText("SEC");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1010, 60, 190, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsfinalproject/giphy.gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(750, 150, 370, 370);

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Courier New", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Time of Quick:");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(400, 60, 200, 40);

        jLabel15.setBackground(new java.awt.Color(204, 0, 51));
        jLabel15.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 51));
        jLabel15.setText("SEC");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(600, 60, 190, 40);

        backImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsfinalproject/socialShareImage.img.jpg"))); // NOI18N
        backImage.setText("jLabel1");
        backImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backImageMouseEntered(evt);
            }
        });
        getContentPane().add(backImage);
        backImage.setBounds(0, 0, 1200, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
        System.exit(0);
        this.setDefaultCloseOperation(evt.getKeyCode());
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.startTimeB = System.currentTimeMillis();
       jLabel8.setVisible(true);
//         loading=true;
       this.add(jLabel8);
               BubbleSort ob = new BubbleSort(this);
int[] Array=new int[DSFinalProject.data.size()];
        System.out.println("data size:"+DSFinalProject.data.size());
       for(int m=0;m<DSFinalProject.data.size();m++)
       {
           Array[m]=DSFinalProject.data.get(m);
       }
        ob.bubbleSort(Array);
        System.out.println("Sorted array");
        ob.printArray(Array);
        this.Bubble=true;
         CKB=ob.GetCHKComplexity();
           SPB=ob.GetSwapComplexity();
          this.TimeComplexityB=CKB+SPB;
          if(this.TimeComplexityQ<this.TimeComplexityB)
          {
               jLabel9.setText("  Quick Sort Wins ");
          }
          else if(this.TimeComplexityQ>this.TimeComplexityB)
          {
               jLabel9.setText("  Bubble Sort Wins ");
          }
          else
          {
              jLabel9.setText("   BOTH Sorts same Time Taken ");
          }
           jTextArea4.setText("");
         if(this.Quick&&this.Bubble)
      {
           
            jLabel7.setVisible(true);
         jLabel9.setVisible(true);
         jTextArea4.setText(jTextArea4.getText()+"\n\nBubble Sort \n\nChecks Comlexity: "+CKB+"\nSwaps Compexity: "+SPB+"\nTime Complexity: "+this.TimeComplexityB);
            jTextArea4.setText(jTextArea4.getText()+"\n\nQuick Sort \n\nChecks Comlexity: "+CKQ+"\nSwaps Compexity: "+SPQ+"\nTime Complexity: "+this.TimeComplexityQ);
     this.Bubble=false;
      }
         this.endTimeB = System.currentTimeMillis();
       this.timeB = (this.endTimeB - this.startTimeB) / 1000.0;
        jLabel8.setVisible(false);
//         loading=false;
         jLabel14.setText(Double.toString(timeB)+" SEC");
        this.add(jLabel8);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         startTimeQ = System.currentTimeMillis();
        jLabel8.setVisible(true);
        this.add(jLabel8);
//        loading=true;
        int n = DSFinalProject.Array2.length; 

		  MyQuickSort ob = new   MyQuickSort(this); 
		ob.sort(DSFinalProject.Array2, 0, n-1); 

		System.out.println("sorted array"); 
		ob.printArray(DSFinalProject.Array2); 
//        MyQuickSort sorter = new MyQuickSort(this);
//
//        sorter.sort(DSFinalProject.Array2);
//
//      sorter.printArray();
       CKQ=ob.GetCHKComplexity();
           SPQ=ob.GetSwapComplexity();
          this.TimeComplexityQ=CKQ+SPQ;
          if(this.TimeComplexityQ<this.TimeComplexityB)
          {
               jLabel9.setText(" Quick Sort Wins ");
          }
          else if(this.TimeComplexityQ>this.TimeComplexityB)
          {
               jLabel9.setText("Bubble Sort Wins ");
          }
          else
          {
              jLabel9.setText("   BOTH Sorts same Time Taken ");
          }
      this.Quick=true;
        jTextArea4.setText("");
      if(this.Quick&&this.Bubble)
      {
          
        
            jLabel7.setVisible(true);
         jLabel9.setVisible(true);
         jTextArea4.setText(jTextArea4.getText()+"\n\nQuick Sort \n\nChecks Comlexity: "+CKQ+"\nSwaps Compexity: "+SPQ+"\nTime Complexity: "+this.TimeComplexityQ);
           jTextArea4.setText(jTextArea4.getText()+"\n\nBubble Sort \n\nChecks Comlexity: "+CKB+"\nSwaps Compexity: "+SPB+"\nTime Complexity: "+this.TimeComplexityB);
          this.Quick=false;
      }
         endTimeQ = System.currentTimeMillis();
        timeQ = (endTimeQ - startTimeQ) / 1000.0;
          jLabel15.setText(Double.toString(timeQ)+" SEC");
//           loading=false;
            jLabel8.setVisible(false);
            this.add(jLabel8);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      jLabel8.setVisible(true);
//       loading=true;
      this.add(jLabel8);
        try {
            // TODO add your handling code here:
System.out.println(" no :"+jTextField1.getText());
            int numm=Integer.parseInt(jTextField1.getText());
            if(numm<=2147483647)
            {
                new RandomFileGenerator( numm);
                JOptionPane.showMessageDialog(this, "File is created "," ",JOptionPane.DEFAULT_OPTION);
        
            }
            else{
                 JOptionPane.showMessageDialog(this, "MAX no Reached please enter less then 2147483647, please try again later.! "," Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel8.setVisible(false);
//         loading=false;
        this.add(jLabel8);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jLabel8.setVisible(true);
//         loading=true;
        this.add(jLabel8);
         ArrayList<Integer> data= new ArrayList<Integer>(); 
         data.clear();
          jTextArea2.setText("");
            jLabel7.setVisible(false);
         jLabel9.setVisible(false);
         jTextArea4.setText("");
            FileReader fr=null; 
        try
        { 
            fr = new FileReader("output.txt"); 
        } 
        catch (FileNotFoundException fe) 
        { 
            System.out.println("File not found"); 
        } 
        int f=0;
  
        // read from FileReader till the end of file 
  BufferedReader br=new BufferedReader(fr);    
  
          int i;  
          String num="";
                  int number=0;
        try {
            while((i=br.read())!=-1){
                
                if((char)i==',')
                {
                    number =Integer.parseInt( num);
                    
                    this.appendT2(""+number+"\n");
                    data.add(number);
                    
                    num="";
                }
                else
                {
                    num+=(char)i;
                }
                
            }  
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        DSFinalProject.data=data;
       
    DSFinalProject.Array1=new int[data.size()];
        System.out.println("data size:"+data.size());
       for(int m=0;m<data.size();m++)
       {
           Array1[m]=data.get(m);
       }
      DSFinalProject.Array2=DSFinalProject.Array1;
         
    jLabel8.setVisible(false);
    this.add(jLabel8);
//     loading=false;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        // TODO add your handling code here:
        System.exit(0);
//        this.setDefaultCloseOperation(evt.getKeyCode());
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void backImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backImageMouseEntered
        // TODO add your handling code here:
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setForeground(new java.awt.Color(0, 204, 204));
        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setForeground(new java.awt.Color(0, 204, 204));
    }//GEN-LAST:event_backImageMouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setForeground(new java.awt.Color(153, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
     jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setForeground(new java.awt.Color(153, 255, 255));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setForeground(new java.awt.Color(153, 255, 255));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setForeground(new java.awt.Color(153, 255, 255));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        // TODO add your handling code here:
        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setForeground(new java.awt.Color(153, 255, 255));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
          jLabel7.setVisible(false);
         jLabel9.setVisible(false);
         jTextArea4.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed
 
    void  appendT1(String ST)
 {
    this.jTextArea1.append(ST);
 }
 void  appendT2(String ST)
 {
    this.jTextArea2.append(ST);
 }
 void  appendT3(String ST)
 {
    this.jTextArea3.append(ST);
 }
  void  emptyT1()
 {
    this.jTextArea1.setText("");
 }
 void  emptyT2()
 {
    this.jTextArea2.setText("");
 }
 void  emptyT3()
 {
    this.jTextArea3.setText("");
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
